development: &development
  listen: 3000
  redis: &redis
    detect_buffers: true
    host: localhost
    port: 6379

development-test:
    <<: *development
    redis:
        <<: *redis
        select: 1
